spring:
  datasource:
    url: jdbc:mysql://172.18.88.38:3306/game?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: game_admin
    password: 123
mybatis:
  type-aliases-package: net.xc.pojo
  mapper-locations: classpath:xml/*Mapper.xml
  config-location: classpath:mybatis-config.xml